let datos = [{
    "id": 1,
    "first_name": "Gaston",
    "last_name": "Cossington",
    "email": "gcossington0@army.mil",
    "gender": "Male",
    "ip_address": "119.176.52.185"
  }, {
    "id": 2,
    "first_name": "Gan",
    "last_name": "Hargerie",
    "email": "ghargerie1@geocities.jp",
    "gender": "Male",
    "ip_address": "202.124.46.95"
  }, {
    "id": 3,
    "first_name": "Locke",
    "last_name": "Farrimond",
    "email": "lfarrimond2@mlb.com",
    "gender": "Male",
    "ip_address": "112.18.194.160"
  }, {
    "id": 4,
    "first_name": "Siusan",
    "last_name": "Bleakley",
    "email": "sbleakley3@earthlink.net",
    "gender": "Female",
    "ip_address": "218.154.23.139"
  }, {
    "id": 5,
    "first_name": "Harrie",
    "last_name": "Setford",
    "email": "hsetford4@drupal.org",
    "gender": "Female",
    "ip_address": "232.34.52.233"
  }, {
    "id": 6,
    "first_name": "Vincenty",
    "last_name": "Alps",
    "email": "valps5@icq.com",
    "gender": "Male",
    "ip_address": "148.226.210.112"
  }, {
    "id": 7,
    "first_name": "Reagen",
    "last_name": "Arstall",
    "email": "rarstall6@house.gov",
    "gender": "Male",
    "ip_address": "247.105.33.219"
  }, {
    "id": 8,
    "first_name": "Roarke",
    "last_name": "Letherbury",
    "email": "rletherbury7@example.com",
    "gender": "Male",
    "ip_address": "86.66.176.81"
  }, {
    "id": 9,
    "first_name": "Merci",
    "last_name": "Povele",
    "email": "mpovele8@soup.io",
    "gender": "Female",
    "ip_address": "131.40.146.126"
  }, {
    "id": 10,
    "first_name": "Rurik",
    "last_name": "Pimmocke",
    "email": "rpimmocke9@ibm.com",
    "gender": "Male",
    "ip_address": "99.119.159.129"
  }, {
    "id": 11,
    "first_name": "Nahum",
    "last_name": "Cunrado",
    "email": "ncunradoa@ca.gov",
    "gender": "Male",
    "ip_address": "61.235.42.237"
  }, {
    "id": 12,
    "first_name": "Rickey",
    "last_name": "Melladew",
    "email": "rmelladewb@mapy.cz",
    "gender": "Male",
    "ip_address": "65.146.147.214"
  }, {
    "id": 13,
    "first_name": "Wait",
    "last_name": "Syme",
    "email": "wsymec@bigcartel.com",
    "gender": "Male",
    "ip_address": "126.150.34.37"
  }, {
    "id": 14,
    "first_name": "Sheffield",
    "last_name": "Lyste",
    "email": "slysted@apple.com",
    "gender": "Male",
    "ip_address": "251.138.54.91"
  }, {
    "id": 15,
    "first_name": "Agace",
    "last_name": "Denerley",
    "email": "adenerleye@oaic.gov.au",
    "gender": "Female",
    "ip_address": "117.185.16.199"
  }, {
    "id": 16,
    "first_name": "Joelynn",
    "last_name": "Harefoot",
    "email": "jharefootf@hexun.com",
    "gender": "Female",
    "ip_address": "96.139.157.185"
  }, {
    "id": 17,
    "first_name": "Koralle",
    "last_name": "Riquet",
    "email": "kriquetg@apache.org",
    "gender": "Female",
    "ip_address": "139.142.59.228"
  }, {
    "id": 18,
    "first_name": "Burgess",
    "last_name": "Josowitz",
    "email": "bjosowitzh@seattletimes.com",
    "gender": "Male",
    "ip_address": "30.181.106.40"
  }, {
    "id": 19,
    "first_name": "Guinna",
    "last_name": "Rattenbury",
    "email": "grattenburyi@gov.uk",
    "gender": "Bigender",
    "ip_address": "44.100.23.5"
  }, {
    "id": 20,
    "first_name": "Kara",
    "last_name": "Chable",
    "email": "kchablej@thetimes.co.uk",
    "gender": "Non-binary",
    "ip_address": "219.236.74.167"
  }, {
    "id": 21,
    "first_name": "Woody",
    "last_name": "Cannan",
    "email": "wcannank@sogou.com",
    "gender": "Male",
    "ip_address": "255.102.93.197"
  }, {
    "id": 22,
    "first_name": "Barbey",
    "last_name": "Diplock",
    "email": "bdiplockl@intel.com",
    "gender": "Female",
    "ip_address": "138.165.3.144"
  }, {
    "id": 23,
    "first_name": "Norene",
    "last_name": "Grichukhin",
    "email": "ngrichukhinm@sciencedaily.com",
    "gender": "Female",
    "ip_address": "98.182.92.6"
  }, {
    "id": 24,
    "first_name": "Gregg",
    "last_name": "Corran",
    "email": "gcorrann@latimes.com",
    "gender": "Male",
    "ip_address": "84.175.96.74"
  }, {
    "id": 25,
    "first_name": "Sasha",
    "last_name": "Capper",
    "email": "scappero@cpanel.net",
    "gender": "Male",
    "ip_address": "205.146.120.9"
  }, {
    "id": 26,
    "first_name": "Marcella",
    "last_name": "Morad",
    "email": "mmoradp@reuters.com",
    "gender": "Female",
    "ip_address": "52.200.82.54"
  }, {
    "id": 27,
    "first_name": "Alberta",
    "last_name": "Gamlen",
    "email": "agamlenq@google.com.br",
    "gender": "Female",
    "ip_address": "159.167.61.173"
  }, {
    "id": 28,
    "first_name": "Leslie",
    "last_name": "Veracruysse",
    "email": "lveracruysser@pen.io",
    "gender": "Genderqueer",
    "ip_address": "67.199.74.57"
  }, {
    "id": 29,
    "first_name": "Laetitia",
    "last_name": "Thebes",
    "email": "lthebess@mozilla.com",
    "gender": "Female",
    "ip_address": "83.127.65.127"
  }, {
    "id": 30,
    "first_name": "Briny",
    "last_name": "Klehyn",
    "email": "bklehynt@google.com.au",
    "gender": "Female",
    "ip_address": "141.85.109.74"
  }, {
    "id": 31,
    "first_name": "Allie",
    "last_name": "Swanson",
    "email": "aswansonu@slate.com",
    "gender": "Female",
    "ip_address": "23.224.104.187"
  }, {
    "id": 32,
    "first_name": "Brigida",
    "last_name": "Fettis",
    "email": "bfettisv@altervista.org",
    "gender": "Female",
    "ip_address": "198.128.170.22"
  }, {
    "id": 33,
    "first_name": "Tallie",
    "last_name": "Gildroy",
    "email": "tgildroyw@cyberchimps.com",
    "gender": "Male",
    "ip_address": "145.18.33.43"
  }, {
    "id": 34,
    "first_name": "Katleen",
    "last_name": "Neeves",
    "email": "kneevesx@goo.gl",
    "gender": "Female",
    "ip_address": "155.96.77.106"
  }, {
    "id": 35,
    "first_name": "Dulcea",
    "last_name": "MacKnockiter",
    "email": "dmacknockitery@patch.com",
    "gender": "Female",
    "ip_address": "196.60.38.236"
  }, {
    "id": 36,
    "first_name": "Goldi",
    "last_name": "Coomer",
    "email": "gcoomerz@stumbleupon.com",
    "gender": "Female",
    "ip_address": "27.138.53.229"
  }, {
    "id": 37,
    "first_name": "Ronnie",
    "last_name": "Lippiello",
    "email": "rlippiello10@blogger.com",
    "gender": "Female",
    "ip_address": "246.181.229.58"
  }, {
    "id": 38,
    "first_name": "Adaline",
    "last_name": "Hovee",
    "email": "ahovee11@disqus.com",
    "gender": "Female",
    "ip_address": "14.159.139.245"
  }, {
    "id": 39,
    "first_name": "Lonni",
    "last_name": "Freda",
    "email": "lfreda12@chicagotribune.com",
    "gender": "Female",
    "ip_address": "187.5.113.67"
  }, {
    "id": 40,
    "first_name": "Lyndsay",
    "last_name": "Coase",
    "email": "lcoase13@com.com",
    "gender": "Female",
    "ip_address": "202.17.165.55"
  }, {
    "id": 41,
    "first_name": "Gun",
    "last_name": "Ashlee",
    "email": "gashlee14@paginegialle.it",
    "gender": "Male",
    "ip_address": "28.21.255.252"
  }, {
    "id": 42,
    "first_name": "Isa",
    "last_name": "Batchley",
    "email": "ibatchley15@salon.com",
    "gender": "Female",
    "ip_address": "148.102.236.118"
  }, {
    "id": 43,
    "first_name": "Julietta",
    "last_name": "Rumens",
    "email": "jrumens16@youtu.be",
    "gender": "Female",
    "ip_address": "125.57.121.177"
  }, {
    "id": 44,
    "first_name": "Lorette",
    "last_name": "Frigout",
    "email": "lfrigout17@squarespace.com",
    "gender": "Female",
    "ip_address": "204.34.152.116"
  }, {
    "id": 45,
    "first_name": "Sherye",
    "last_name": "Braitling",
    "email": "sbraitling18@zimbio.com",
    "gender": "Agender",
    "ip_address": "24.176.245.135"
  }, {
    "id": 46,
    "first_name": "Karee",
    "last_name": "Sollars",
    "email": "ksollars19@senate.gov",
    "gender": "Female",
    "ip_address": "5.118.14.219"
  }, {
    "id": 47,
    "first_name": "Brandise",
    "last_name": "Camden",
    "email": "bcamden1a@squidoo.com",
    "gender": "Female",
    "ip_address": "242.152.93.101"
  }, {
    "id": 48,
    "first_name": "Calli",
    "last_name": "Hanscombe",
    "email": "chanscombe1b@techcrunch.com",
    "gender": "Genderfluid",
    "ip_address": "202.119.134.192"
  }, {
    "id": 49,
    "first_name": "Norean",
    "last_name": "Kobisch",
    "email": "nkobisch1c@google.de",
    "gender": "Female",
    "ip_address": "128.175.4.62"
  }, {
    "id": 50,
    "first_name": "Donnell",
    "last_name": "Redfern",
    "email": "dredfern1d@dailymotion.com",
    "gender": "Male",
    "ip_address": "2.147.23.28"
  }];

let numeros = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

function esPar(n) {
    return n % 2 === 0;
}

// console.log(numeros);
// console.log(esPar(3));
// console.log(esPar(6));

console.log(numeros.filter(esPar));

console.log(numeros.filter( x => x % 2 == 0))
console.log(numeros.filter( x => x % 2 !== 0))

/*
console.log(datos
    .filter(persona => persona.gender === "Female")
    .map(persona => persona.first_name)
)
*/

console.log(
    datos
        .map(persona => persona.gender)
        .sort() // ordenar por órden alfabético
)